version: "3.8"

services:
  app:
    image: golang:1.17
    container_name: go_app
    working_dir: /go/src/app
    volumes:
      - .:/go/src/app
    command: go run main.go
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
